### ISSUE TITLE
strange naming

### ISSUE THREAD

**Issue by PierreDurrr** [hollanbm/renamarr#79]
![image](https://github.com/user-attachments/assets/9feb1308-81a2-4bc5-a583-a10f7048a3ec)

Someone got this ?

**Comment by PierreDurrr** [comment]
Crap. Except Tdarr i can't think of anything that could mess...

**Comment by hollanbm** [comment]
> Crap. Except Tdarr i can't think of anything that could mess...

Do you have any filename modifications in your tdarr pipeline?

Tdarr could process the file, rename it. renamarr runs, and initiates a scan, finds the newly named episode and renames it back. Then tdarr detects a new change, and the cycle repeats.

I've run into something like the above a few times now.

An easy test, is to stop tdarr for a few hours, and see if the file is still being renamed

**Comment by PierreDurrr** [comment]
Yeah, will check this way. Strangely, tdarr pipeline for shows and movies are the same, and it seems to only occure with sonarr...
Can we keep this open a bit more ?

**Comment by hollanbm** [comment]
> Yeah, will check this way. Strangely, tdarr pipeline for shows and movies are the same, and it seems to only occure with sonarr...
> 
> Can we keep this open a bit more ?

I don't mind leaving it open if you need some ideas to help track this down.

**Comment by hollanbm** [comment]
I'm going to go ahead and close this out. Hopefully you were able to get this figured out
